### ISSUE TITLE
Allow user to input their own device_name instead of defaulting to "beeper-imessage"

### ISSUE THREAD

**Issue by rollingonchrome** [beeper/imessage#10]
Apple can see the names of devices added to Apple IDs.

Please allow the user to input their own device_name so they can choose something more obscure than "beeper-imessage."

**Comment by tulir** [comment]
https://github.com/beeper/imessage/blob/main/example-config.yaml#L73

**Comment by rollingonchrome** [comment]
Thanks. I have changed the config file but when I run the bridge again the device_name changes back to "beeper-imessage."

Perhaps either better instructions or an option to input the device_name along with the registration code would be an improvement.
