### ISSUE TITLE
Rev MacOs version support for generating an iMessage Registration Code

### ISSUE THREAD

**Issue by ghost** [beeper/imessage#17]
The current version of the library/util does not support MacOS Sonoma 14.3+.

![image](https://github.com/beeper/imessage/assets/89916564/c968f7bb-b8d2-42b1-8aca-f1f9d1838b48)
![image](https://github.com/beeper/imessage/assets/89916564/0ecb725d-42f9-4e2f-a650-2a1eb9c1457b)

I am a software engineer but do not have enough experience with go to be comfortable making the changes needed.

**Comment by tulir** [comment]
The registration provider is https://github.com/beeper/mac-registration-provider and it already supports the latest beta, but it hasn't been released yet
