### ISSUE TITLE
m.room.name

### ISSUE THREAD

**Issue by gabrc52** [beeper/imessage#21]
Unlike the mautrix bridges, this bridge adds the bot to bridged rooms, so they look like group chats with the other person and the iMessage bot

![image](https://github.com/beeper/imessage/assets/24363938/87f4409c-8ec4-4be7-bb2d-0b7e27fdc3dc)

![image](https://github.com/beeper/imessage/assets/24363938/75829174-c18a-4daa-aa6a-ef5350863fa4)

It would be good to set a `m.room.name` so that it shows up OK in the room list.

![image](https://github.com/beeper/imessage/assets/24363938/0faf7df5-2b12-4a40-bf5f-6869e9ef2afd)

**Comment by tulir** [comment]
All the bridges add the bot to bridged rooms when necessary and all also have the `private_chat_portal_meta` option to set room metadata in DM rooms

**Comment by gabrc52** [comment]
Thank you! Closing this issue since it's just a configuration option away.
