### ISSUE TITLE
iMessage bridge, when registering a phone number, repeatedly suggests the same REG-REQ SMS to send to Apple

### ISSUE THREAD

**Issue by Technophilus** [beeper/imessage#3]
On the iMessage bridge, I set up my own relay server, jailbroken iPhone with the beepserv tweak, and beeper imessage bridge. When attempting to register my phone number (and failing for some other reason, such as for example not running the right script), I may send the REG-REQ SMS to Apple and not catch the response. When running `register-phone-number` on the bridge again, it suggests the same message to send. See the following image for an example:

![Message history](https://github.com/beeper/imessage/assets/24627311/6d71bf0b-2c5a-4f69-9aa2-da2f78a6d6a6)

Even deregistering and reregistering ids does not fix this. In my view, this issue is resolved once the iMessage bridge generates a new token for each call of `register-phone-number`.

**Comment by tulir** [comment]
The `logout` command should work. It might also be reasonable to add a separate command to regenerate push keys, but the register-phone-number command will not do that automatically.

**Comment by Technophilus** [comment]
The issue with the `logout` command is that it will then require physical access to the iPhone for 2FA. Additionally, the push keys are not regenerated even after a successful registration, so a logout is always required to renew the registration.

**Comment by tulir** [comment]
If the registration is successful there's no need to register it again

**Comment by Technophilus** [comment]
> If the registration is successful there's no need to register it again

so, then the phone number registration will never expire? Good to know. That makes everything a whole lot simpler. Thanks.

**Comment by tulir** [comment]
Yes, the SMS auth is valid for 10 years (no idea what happens after that). IDS registration has to be redone relatively often (that's what registration data is for), but that's automatic.
